name: C/C++ CI

on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: sync bitbucket
      run: git push --mirror https://x-token-auth:ATCTT3xFfGN0ZogGRCJr2otvveCYH10arfEk4cTtpPngQRrf6Apbm5m71ou3iexp5Sz-LlyW8rmMrma-E5ABQ84m0CxOrHVwzl2n6Pkcr6F5fk8pCLfdXqtQZoQY2kutceVCrlbiZ3q5zjhXCU7Y8ZTgnq0i48CNrtZDwBFekpP3HNCQsrDN_9s=65BFA5E9@bitbucket.org/sugon2/rocr-runtime.git

